apiVersion: v1
kind: Service
metadata:
  name: {{ template "gitlab-ce.fullname" . }}
#  annotations:
#    service.beta.kubernetes.io/alicloud-loadbalancer-address-type: {{ .Values.service.addresstype }}
#    service.beta.kubernetes.io/alicloud-loadbalancer-id: {{ .Values.service.slbID }}
#    service.beta.kubernetes.io/alicloud-loadbalancer-force-override-listeners: "true"
  labels:
    app: {{ template "gitlab-ce.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  namespace: gitlab
spec:
  ports:
    - port: {{ .Values.service.externalPort }}
      targetPort: {{ .Values.service.internalPort }}
      protocol: HTTP
      name: {{ .Values.service.targetname }}
    - port: {{ .Values.service.externalPort2 }}
      targetPort: {{ .Values.service.internalPort2 }}
      protocol: TCP
      name: {{ .Values.service.targetname2 }}
  selector:
    app: {{ template "gitlab-ce.name" . }}
    release: {{ .Release.Name }}
  type: {{ .Values.service.type }}
